baseURL: http://news.ocscottishrite.org
languageCode: en-us
title: The Orange County Scottish Rite News
theme: "hugo-starter"
enableEmoji: true


menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 100

  - identifier: contact
    name: Contact
    url: /contact/
    weight: 110


markup:
  goldmark:
    renderer:
      unsafe: true
